#!/usr/bin/env bash

clear

root=$(pwd)

for level in .levels/*
do
  . $level
done

function level6 {
  echo
  echo 'Awesome. You'"'"'ve passed all the levels.'
  echo 'You are my hero'
  tput sgr0
  echo
  exit
}

level=0

tput setaf 5
level$level
tput sgr0
echo

while read -r -p 'Tutorial: ('"$(pwd)"')$ ' -e COMMANDS
do
  eval "$COMMANDS" > "$root/.output/last-command"
  cat "$root/.output/last-command"
  history -s "$COMMANDS"
  if "answer$level" "$COMMANDS" "$root/.output/last-command"
  then
    level=$((level+1))
    tput setaf 5
    level$level
    tput sgr0
  fi
done
