#!/usr/bin/env bash

function level0 {
  echo
  echo 'Welcome to the GDS interactive command line tutorial.'
  echo 'We'"'"'re going to walk you through using the unix command line'
  echo
  echo 'First, lets learn about some simple commands'
  echo '`ls` lists the files in the current directory'
  echo 'To run `ls` simply type "ls" and press enter:'
  echo
}
function answer0 {
  actual="$1"
  expected="ls"

  output_sum=$(shasum "$2" | awk '{ print $1 }')
  expected_output_sum="f6fd1656d79b06918bb5cf85c8bae58c3884deaf"

  # If the command was exactly as expected, or if the output exactly matches the expected output then on we go to the next level

  if [[ "$actual" == "$expected" ]] || [[ "$output_sum" == "$expected_output_sum" ]]
  then
    return 0
  else
    return 1
  fi
}
