#!/usr/bin/env bash

function level0 {
  echo
  echo 'Welcome to the GDS interactive command line tutorial.'
  echo 'We'"'"'re going to walk you through using the unix command line'
  echo
  echo 'First, lets learn about some simple commands'
  echo '`ls` lists the files in the current directory'
  echo 'To run `ls` simply type "ls" and press enter:'
  echo
}
function answer0 {
  actual="$1"
  expected="ls"
  if [ "$actual" == "$expected" ]
  then
    return 0
  else
    return 1
  fi
}
