#!/usr/bin/env bash

function level1 {
  echo
  echo 'Minto. See the output above, that'"'"'s a list of the files in this directory. Badass.'
  echo
  echo '`ls` is just a program. Most programs can take "arguments". Arguments are provided separated by spaces after the program.'
  echo 'You can tell `ls` to list the contents of a particulatar directory by providing the path to the directory as an argument.'
  echo 'Let'"'"'s find out about the contents of that "files" directory...'
  echo
  echo 'Try `ls files`'
  echo
}
function answer1 {
  actual="$1"
  expected="ls files"

  output_sum=$(shasum "$2" | awk '{ print $1 }')
  expected_output_sum="6f182bfb45532b6e65065f1234165543acd2aee6"

  if [[ "${DEBUG:-false}" == 'true' ]] && [[ "$output_sum" != "$expected_output_sum" ]]
  then
    echo "$output_sum did not match $expected_output_sum"
  fi

  if [[ "$actual" == "$expected"* ]] || [[ "$output_sum" == "$expected_output_sum" ]]
  then
    return 0
  else
    return 1
  fi
}
