#!/usr/bin/env bash

function level2 {
  echo
  echo 'Ok, so there'"'"'s another directory called "animals" inside "files".'
  echo
  echo 'You can provide a path to nested directories by separating them by forward slashes (/).'
  echo
  echo 'Try `ls files/animals`'
  echo
}
function answer2 {
  actual="$1"
  expected="ls files/animals"

  output_sum=$(shasum "$2" | awk '{ print $1 }')
  expected_output_sum="1c71353f5c46944a0a365547d0cfad99244828eb"

  if [[ "${DEBUG:-false}" == 'true' ]] && [[ "$output_sum" != "$expected_output_sum" ]]
  then
    echo "$output_sum did not match $expected_output_sum"
  fi

  if [[ "$actual" == "$expected"* ]] || [[ "$output_sum" == "$expected_output_sum" ]]
  then
    return 0
  else
    return 1
  fi
}
